{{- if .Values.configMaps }}
{{- range $name, $path := .Values.configMaps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.namespace }}
data:
  {{ base $path }}: |-
    {{ $.Files.Get $path | indent 4 }}
---
{{- end }}
{{- end }}