{{- if .Values.configMaps }}
{{- range .Values.configMaps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}-config
  namespace: {{ $.Values.namespace }}
data:
{{- $files := $.Files.Glob .path }}
{{- range $path, $file := $files }}
  {{ base $path }}: |-
{{ $file | indent 4 }}
{{- end }}
---
{{- end }}
{{- end }}