{{- range $name, $glob := .Values.configMaps }}
  {{- $files := $.Files.Glob $glob }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}-config
  namespace: {{ $.Values.namespace }}
data:
  {{- range $path, $file := $files }}
  {{ base $path }}: |-
  {{ $file | toString | indent 4 }}
  {{- end }}
---
{{- end }}