apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.ports }}
          ports:
          {{- range .Values.ports  }}
            - containerPort: {{ . }}
          {{- end }}
          {{ - if .Values.env }}
          env:
          {{ - range .Values.env }}
          - name: {{ .name }}
            value: {{ .value }}
          {{ - end }}
          {{ - end }}
          volumeMounts:
          {{- range .Values.volumes }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
          {{- end }}
          {{- end }}
      {{- if .Values.volumes }}
      volumes:
      {{- range .Values.volumes }}
        - name: {{ .name }}
          hostPath:
            path: {{ .hostPath }}
            type: DirectoryOrCreate
      {{- end }}
      {{- end }}