{{- if .Values.ports }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.name }}
  ports:
  {{- range .Values.ports }}
    - port: {{ . }}
      targetPort: {{ . }}
  {{- end }}
{{- end }}